### ISSUE TITLE
Hovering stars/installs causes weird drop down menu to appear

### ISSUE THREAD

**Issue by hiimbex** [probot/probot.github.io#107]
<img width="319" alt="screen shot 2017-11-20 at 7 14 44 pm" src="https://user-images.githubusercontent.com/13410355/33034132-1ddf71da-ce27-11e7-9c23-a193f7e7b48b.png">

I'm using Chrome and can see this on the homepage and /apps page. Not a huge deal, just looks kind of weird.

cc/ @JasonEtco

**Comment by JasonEtco** [comment]
Fascinating. I'll take a look, thanks @hiimbex 👍

**Comment by j-f1** [comment]
Looks like this is caused by the `overflow: hidden` I put on the app card ☹️ . Solutions:

1. Undo this change and apply the same `border-radius` as the app card has to the bottom of the bottom bar.
1. Change the orientation of the tooltips (`n`? `w` for the left two and `e` for the ones on the avatars?)

**Comment by JasonEtco** [comment]
@j-f1 it looks like just removing `overflow: hidden` does the trick. Do you want to make that PR?
