### ISSUE TITLE
Add Events and Actions to Probot Website

### ISSUE THREAD

**Issue by aps120797** [probot/probot.github.io#156]
Add GitHub events and related actions to the [docs of Probot].(https://probot.github.io/docs/)
One thing, as a beginner to Probot that I felt was missing in Probot docs was GitHub events and it's related actions.
A URL of the GitHub webhook events has been added in the docs (https://developer.github.com/webhooks/#events), but it doesn't have any information about the the actions associated with the events.
It will be really cool, and really helpful for the beginners if GitHub Events and Action section could be added to (probably in the [Reference section](https://probot.github.io/docs/#reference)) Probot Docs.
Here's a PR for the same: https://github.com/probot/probot/pull/498

**Comment by aps120797** [comment]
This is still relevant. 😄

**Comment by bkeepers** [comment]
@aps120797 Is there anything that we can do to move this forward now?

As we discussed in https://github.com/probot/probot/pull/498, I don't think we should duplicate reference documentation on the probot website because it's guaranteed to become out of date. I think it would be great if we could suggest improvements to developer.github.com.

**Comment by aps120797** [comment]
@bkeepers , I thought of creating a creating a new reference document with the ideas that you have suggested here as you have suggested here: https://github.com/probot/probot/pull/498
But, now, I too think duplicating reference documentation is not a good idea. 
I think I will suggest those changes in [developer.github.com](https://developer.github.com) later.

Thanks for the suggestion. 😄
