### ISSUE TITLE
Document app review process

### ISSUE THREAD

**Issue by bkeepers** [probot/probot.github.io#221]
We currently have some tests and some subjective criteria for evaluating apps, but I'd love to make it really explicit.

For example, here's a few things I do:

1. Open each of the screenshots to ensure they show the specific app functionality as clearly as possible.
1. Install the app on a test organization (I use @robotland for all my app testing)
1. Ensure the app works as advertised

…

I'm sure there's more, but that's a start.

**Comment by hiimbex** [comment]
👍Totally agree we should document this. What you listed has been pretty much what I've been doing so far. I'll admit I slack on actually running the app sometimes, and just skim the repo's code instead.

Additionally I:
- check all links (looking mostly for relative references since folks usually copy form their readme)
- check the repo to confirm docs, license, CoC
- confirm the app slug is actually associated with the app
- check for any written references to being a probot/github app (feels repetitive since they're on the website)
- think about how useful the app functionality is (if I'm on the fence, I'll consult with others)
- read the entire description/how the app works to make sure someone new could figure it out

Also wanted to note, I recently added a [pull request template](https://github.com/probot/probot.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md) mirroring the requirements outlined in our contributing for listing new apps.
